set(WRONGBREW_BIN "$ENV{HOME}/wrongbrew.sh")

execute_process(COMMAND "${WRONGBREW_BIN}" --prefix
	RESULT_VARIABLE DETECT_WRONGBREW
	OUTPUT_VARIABLE WRONGBREW_PREFIX
	ERROR_QUIET
	OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(COMMAND "${WRONGBREW_BIN}" --prefix qt@5
	OUTPUT_VARIABLE QT_PREFIX
	ERROR_QUIET
	OUTPUT_STRIP_TRAILING_WHITESPACE)

if(DETECT_WRONGBREW EQUAL 0)
	list(APPEND CMAKE_PREFIX_PATH "${WRONGBREW_PREFIX};${QT_PREFIX}")
	set(CMAKE_APPLE_SILICON_PROCESSOR arm64)
    set(CMAKE_FIND_ROOT_PATH "${WRONGBREW_PREFIX}")
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
else()
	message(FATAL_ERROR "Could not invoke \"${WRONGBREW_BIN}\" --prefix")
endif()

