---
name: build
'on': [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linux-x86_64:
    name: testing
    runs-on: ubuntu-24.04
    steps:
      - name: Configure git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run test
        run: |
          git log -1 --pretty=format:"%H"
          git log --oneline -n 5
