---
name: build
'on': [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  linux:
    name: linux
    runs-on: ubuntu-20.04
    env:
      CMAKE_OPTS: >-
        -DUSE_WERROR=ON
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
        -DUSE_COMPILE_CACHE=ON
      CCACHE_MAXSIZE: 0
      CCACHE_NOCOMPRESS: 1
      MAKEFLAGS: -j2
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up dpkg architecture
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -qq
          sudo apt-get install libgd3 libpcre2-8-0:i386 libgd3:i386 libselinux1:i386 libmount1:i386 libfaudio0:i386 libglib2.0-0:i386 libgphoto2-6:i386 libgstreamer-plugins-base1.0-0:i386 libgstreamer1.0-0:i386 libodbc1:i386 libsane:i386 gstreamer1.0-plugins-good:i386 libwine:i386
      - name: Install dependencies
        run: xargs -a .github/workflows/deps-linux-x86_64.txt sudo apt-get install --yes 
      - name: Cache ccache data
        uses: actions/cache@v3
        with:
          key: ccache-${{ github.job }}-${{ github.ref }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ github.job }}-${{ github.ref }}-
            ccache-${{ github.job }}-
          path: ~/.ccache
      - name: Configure
        run: |
          ccache --zero-stats
          source /opt/qt5*/bin/qt5*-env.sh || true
          mkdir build && cd build
          cmake .. $CMAKE_OPTS -DCMAKE_INSTALL_PREFIX=./install
      - name: Build
        run: cmake --build build
      - name: Build tests
        run: cmake --build build --target tests
      - name: Run tests
        run: build/tests/tests
      - name: Package
        run: |
          cmake --build build --target install
          cmake --build build --target appimage
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: build/lmms-*.AppImage
      - name: Trim ccache and print statistics
        run: |
          ccache --cleanup
          echo "[ccache config]"
          ccache --show-config
          echo "[ccache stats]"
          ccache --show-stats
        env:
          CCACHE_MAXSIZE: 500M
